### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by byposeidon** [alinja/snipsa#6]
Hello,
The application gives error as below.

ubuntu@ubuntu:~/snipsa$ python3 haploy_find.py raw.csv
Loading DB2...
Traceback (most recent call last):
  File "haploy_find.py", line 54, in <module>
    haploy.load_db2j(min_tree_load_level=min_tree_load_level)
  File "/home/ubuntu/snipsa/haploy.py", line 732, in load_db2j
    with open(fname, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'haploy_map2j.txt'

ubuntu@ubuntu:~/snipsa$ sudo python3 haploy_db_import.py
Loading SNP DB from ISOGG csv...
Traceback (most recent call last):
  File "haploy_db_import.py", line 11, in <module>
    haploy.load_snp()
  File "/home/ubuntu/snipsa/haploy.py", line 474, in load_snp
    with open('SNP Index - Human.csv') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'SNP Index - Human.csv'

**Comment by alinja** [comment]
The first parameter is a 23andme or such file, or one imported from a bam file. Try the GUI.

You need to import the database first. The easy way is to  use the imported database in the release zip, but if you want to import yourself, you need to read the source code to see the input file requirements and where to get them.

**Comment by byposeidon** [comment]
Thank you so much.
